name: Test Auto Pr

on:
  repository_dispatch:
    types: [test]

jobs:
  webhook_test:
    env:
      CommonString: Common Rivision
      LwString: Lw Rivision
    runs-on: ubuntu-latest
    
    steps:
      # feature 브랜치 체크아웃
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Echo Test
        run: echo "$CommonString $LwString"
        
        
      # base 브랜치와 TITLE이 같은 PR이 있는지 체크
      
      # 똑같은 Project의 PR이라면 PR 삭제, 브랜치 제거
#       - name: DeletePr
#         run: gh pr close {branch} | 원격 브랜치 제거 | 로컬 브랜치 체크아웃
      # 아니라면 해당 PR로 체크아웃 
#         - name: ChekoutPr
#           run: gh pr checkout {branch}
      
      # 리비전 다운로드 및 다국어 적용
      
      
      # 푸시 
      
      
      # PR 체크아웃 한게 아니라면 PR 생성
  
