name: Test Auto Pr

on:
  repository_dispatch:
    types: [test]

jobs:
  webhook_test:
    env:
      CommonString: Common Rivision
      LwString: Lw Rivision
    runs-on: ubuntu-latest
    
    steps:
      # feature 브랜치 체크아웃
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Echo Test
        run: echo "$CommonString $LwString"
  
