name: Test Auto Pr

on:
  repository_dispatch:
    types: [test]

jobs:
  webhook_test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          if ! command -v jq > /dev/null 2>&1
          then
          sudo apt update
          sudo apt install -y jq
          fi
          jq --version
          
      - name: echoTest
        run: |

          read CUR_PROJECT_ID CUR_BRANCH_ID CUR_PROJECT_REVISION URL < <(echo '${{ toJson(github.event.client_payload) }}' | jq '. | {projectId: .projectId, branchId: .branchId, revision: .revision, url: .exportFileList[]|select(.exportType == "ANDROID")|.url }' | jq -r '.projectId, .branchId, .revision, .url')
          
          echo "CUR_PROJECT_ID = $CUR_PROJECT_ID"
          echo "CUR_BRANCH_ID = $CUR_PROJECT_REVISION"
          echo "url = $URL"
        
      
  
