name: Test Auto Pr

on:
  repository_dispatch:
    types: [test]

jobs:
  webhook_test:
    runs-on: ubuntu-latest
    env:
      DATA: ${{ github.event.client_payload }}
      USER: ${{ github.event.client_payload.releaseUser }}
    
    steps:
      - name: setup
        run: |
          if ! command -v jq > /dev/null 2>&1
          then
          sudo apt update
          sudo apt install -y jq
          fi
          jq --version
          
      - name: echoTest
        run: |
          echo ${{ env.DATA }}
          echo ${{ env.USER }}
          
          echo "test = $test"
          read CUR_PROJECT_ID CUR_BRANCH_ID CUR_PROJECT_REVISION URL < <(echo $( ${{ github.event.client_payload }} | jq '. | {projectId: .projectId,branchId: .branchId, revision: .revision, url: .exportFileList[]|select(.exportType == "ANDROID")|.url }' | jq -r '.projectId, .branchId, .revision, .url'))
          echo $CUR_PROJECT_ID
          echo $CUR_PROJECT_REVISION
          echo $URL
        
      
  
